package BaKapp.Movil.Tag;


import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.BALayout;
import anywheresoftware.b4a.debug.*;

public class variables {
private static variables mostCurrent = new variables();
public static Object getObject() {
    throw new RuntimeException("Code module does not support this method.");
}
 public anywheresoftware.b4a.keywords.Common __c = null;
public static anywheresoftware.b4a.objects.collections.Map _global_row_usuario_activo = null;
public static anywheresoftware.b4a.objects.collections.Map _global_row_estacionbk = null;
public static anywheresoftware.b4a.objects.collections.Map _global_row_modalidad = null;
public static anywheresoftware.b4a.objects.collections.Map _global_row_configuracion_general = null;
public static anywheresoftware.b4a.objects.collections.Map _global_row_configuracion_estacion = null;
public static anywheresoftware.b4a.objects.collections.Map _global_row_dolar = null;
public static anywheresoftware.b4a.objects.collections.Map _global_row_moneda = null;
public static String _global_version_bakapp = "";
public static String _global_basebk = "";
public static String _global_ip_webservice = "";
public static boolean _global_sesion_star = false;
public static String _global_iddispositivo = "";
public static String _gl_empresa = "";
public static String _gl_modalidad = "";
public static String _gl_sucursal = "";
public static String _gl_bodega = "";
public static String _gl_caja = "";
public static String _gl_lista_precios = "";
public static String _gl_lista_costos = "";
public static String _gl_fecha_servidor = "";
public static String _gl_nombreempresa = "";
public static anywheresoftware.b4a.objects.collections.List _global_listas_precios_usuario = null;
public static anywheresoftware.b4a.objects.collections.Map _global_row_entidad_x_defecto = null;
public static anywheresoftware.b4a.sql.SQL _vsql = null;
public static boolean _global_existetabla_ms_gateway_stock = false;
public static anywheresoftware.b4a.objects.collections.Map _global_cov = null;
public static anywheresoftware.b4a.objects.collections.Map _global_nvv = null;
public static anywheresoftware.b4a.objects.collections.Map _global_blv = null;
public static anywheresoftware.b4a.objects.collections.Map _global_fcv = null;
public static anywheresoftware.b4a.objects.collections.List _global_sis_despachosimple_docdestino = null;
public static anywheresoftware.b4a.objects.collections.List _global_sis_despachosimple_tipo = null;
public static anywheresoftware.b4a.objects.collections.List _global_sis_despachosimple_tipopago = null;
public b4a.example.dateutils _dateutils = null;
public BaKapp.Movil.Tag.main _main = null;
public BaKapp.Movil.Tag.frm_impresion _frm_impresion = null;
public BaKapp.Movil.Tag.frm_etiquetas _frm_etiquetas = null;
public BaKapp.Movil.Tag.buscar_entidad _buscar_entidad = null;
public BaKapp.Movil.Tag.buscar_productos _buscar_productos = null;
public BaKapp.Movil.Tag.conf_local _conf_local = null;
public BaKapp.Movil.Tag.dbutils _dbutils = null;
public BaKapp.Movil.Tag.frm_buscar_documento _frm_buscar_documento = null;
public BaKapp.Movil.Tag.frm_documentos_generados _frm_documentos_generados = null;
public BaKapp.Movil.Tag.frm_editar_obsoc _frm_editar_obsoc = null;
public BaKapp.Movil.Tag.frm_infostockxprod _frm_infostockxprod = null;
public BaKapp.Movil.Tag.frm_menu_post_venta _frm_menu_post_venta = null;
public BaKapp.Movil.Tag.frm_menu_principal _frm_menu_principal = null;
public BaKapp.Movil.Tag.frm_post_01_descuentos _frm_post_01_descuentos = null;
public BaKapp.Movil.Tag.frm_post_01_formulario _frm_post_01_formulario = null;
public BaKapp.Movil.Tag.frm_post_01_producto _frm_post_01_producto = null;
public BaKapp.Movil.Tag.funciones _funciones = null;
public BaKapp.Movil.Tag.httputils2service _httputils2service = null;
public BaKapp.Movil.Tag.xuiviewsutils _xuiviewsutils = null;
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 3;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 7;BA.debugLine="Public Global_Row_Usuario_Activo As Map";
_global_row_usuario_activo = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 8;BA.debugLine="Public Global_Row_EstacionBk As Map";
_global_row_estacionbk = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 9;BA.debugLine="Public Global_Row_Modalidad As Map";
_global_row_modalidad = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 10;BA.debugLine="Public Global_Row_Configuracion_General As Map";
_global_row_configuracion_general = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 11;BA.debugLine="Public Global_Row_Configuracion_Estacion As Map";
_global_row_configuracion_estacion = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 13;BA.debugLine="Public Global_Row_Dolar As Map";
_global_row_dolar = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 14;BA.debugLine="Public Global_Row_Moneda As Map";
_global_row_moneda = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 16;BA.debugLine="Public Global_Version_BakApp As String";
_global_version_bakapp = "";
 //BA.debugLineNum = 17;BA.debugLine="Public Global_BaseBk As String";
_global_basebk = "";
 //BA.debugLineNum = 19;BA.debugLine="Public Global_Ip_WebService As String";
_global_ip_webservice = "";
 //BA.debugLineNum = 21;BA.debugLine="Public Global_Sesion_Star As Boolean";
_global_sesion_star = false;
 //BA.debugLineNum = 22;BA.debugLine="Public Global_IdDispositivo As String";
_global_iddispositivo = "";
 //BA.debugLineNum = 24;BA.debugLine="Public Gl_Empresa As String";
_gl_empresa = "";
 //BA.debugLineNum = 25;BA.debugLine="Public Gl_Modalidad As String";
_gl_modalidad = "";
 //BA.debugLineNum = 26;BA.debugLine="Public Gl_Sucursal As String";
_gl_sucursal = "";
 //BA.debugLineNum = 27;BA.debugLine="Public Gl_Bodega As String";
_gl_bodega = "";
 //BA.debugLineNum = 28;BA.debugLine="Public Gl_Caja As String";
_gl_caja = "";
 //BA.debugLineNum = 29;BA.debugLine="Public Gl_Lista_Precios As String";
_gl_lista_precios = "";
 //BA.debugLineNum = 30;BA.debugLine="Public Gl_Lista_Costos As String";
_gl_lista_costos = "";
 //BA.debugLineNum = 31;BA.debugLine="Public Gl_Fecha_Servidor As String";
_gl_fecha_servidor = "";
 //BA.debugLineNum = 32;BA.debugLine="Public GL_NombreEmpresa as String";
_gl_nombreempresa = "";
 //BA.debugLineNum = 33;BA.debugLine="Public Global_Listas_Precios_Usuario As List";
_global_listas_precios_usuario = new anywheresoftware.b4a.objects.collections.List();
 //BA.debugLineNum = 34;BA.debugLine="Public Global_Row_Entidad_X_Defecto As Map";
_global_row_entidad_x_defecto = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 36;BA.debugLine="Public vSql As SQL";
_vsql = new anywheresoftware.b4a.sql.SQL();
 //BA.debugLineNum = 37;BA.debugLine="Public Global_ExisteTabla_MS_GATEWAY_STOCK As Boo";
_global_existetabla_ms_gateway_stock = false;
 //BA.debugLineNum = 39;BA.debugLine="Public Global_COV As Map";
_global_cov = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 40;BA.debugLine="Public Global_NVV As Map";
_global_nvv = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 41;BA.debugLine="Public Global_BLV As Map";
_global_blv = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 42;BA.debugLine="Public Global_FCV As Map";
_global_fcv = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 44;BA.debugLine="Public Global_Sis_DespachoSimple_DocDestino As Li";
_global_sis_despachosimple_docdestino = new anywheresoftware.b4a.objects.collections.List();
 //BA.debugLineNum = 45;BA.debugLine="Public Global_Sis_DespachoSimple_Tipo As List";
_global_sis_despachosimple_tipo = new anywheresoftware.b4a.objects.collections.List();
 //BA.debugLineNum = 46;BA.debugLine="Public Global_Sis_DespachoSimple_TipoPago As List";
_global_sis_despachosimple_tipopago = new anywheresoftware.b4a.objects.collections.List();
 //BA.debugLineNum = 48;BA.debugLine="End Sub";
return "";
}
}
